name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '▶ Dependency updates'
    labels:
      - 'dependency-update'

template: |
  ## What’s Changed
  
  $CHANGES
