queue_rules:
  - name: default
    conditions:
      - status-success=build (11, 2.12.10)
      - status-success=build (17, 2.12.10)

pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [tomasherman]
      label:
        add: [dependency-update]
  - name: Approve scala-steward patches
    conditions:
      - base~=master|series/cats-effect2
      - author=scala-steward
      - status-success=build (11, 2.12.10)
      - status-success=build (17, 2.12.10)
      - body~=labels:.*semver-spec-patch.*
    actions:
      review:
        type: APPROVE
  - name: automatic merge on CI success and review
    conditions:
      - base~=master|series/cats-effect2
      - "#changes-requested-reviews-by=0"
      - status-success=build (11, 2.12.10)
      - status-success=build (17, 2.12.10)
    actions:
      merge:
        method: squash
      delete_head_branch:
        force: true
  - name: automatic update for PR marked as “dependency-update“
    conditions:
      - label="dependency-update"
    actions:
      update:
