pages = [{"l":"index.html","n":"site","t":"site","d":"","k":"static"},
{"l":"com/avast/cloud/datadog4s/helpers.html","n":"com.avast.cloud.datadog4s.helpers","t":"package com.avast.cloud.datadog4s.helpers","d":"com/avast/cloud/datadog4s/helpers","k":"package"},
{"l":"com/avast/cloud/datadog4s/helpers/Repeated$.html","n":"Repeated","t":"object Repeated","d":"com/avast/cloud/datadog4s/helpers/Repeated$","k":"object"},
{"l":"com/avast/cloud/datadog4s/helpers/Repeated$.html","n":"run","t":"def run[F[_]](delay: Duration, iterationTimeout: Duration, errorHandler: Throwable => F[Unit])(task: F[Unit])(using evidence$1: Temporal[F]): Resource[F, F[Outcome[F, Throwable, Unit]]]","d":"com/avast/cloud/datadog4s/helpers/Repeated$","k":"def"},
{"l":"com/avast/datadog4s.html","n":"com.avast.datadog4s","t":"package com.avast.datadog4s","d":"com/avast/datadog4s","k":"package"},
{"l":"com/avast/datadog4s/StatsDMetricFactory$.html","n":"StatsDMetricFactory","t":"object StatsDMetricFactory","d":"com/avast/datadog4s/StatsDMetricFactory$","k":"object"},
{"l":"com/avast/datadog4s/StatsDMetricFactory$.html","n":"fromClient","t":"def fromClient[F[_]](client: StatsDClient, config: StatsDMetricFactoryConfig)(using evidence$2: Sync[F]): MetricFactory[F]","d":"com/avast/datadog4s/StatsDMetricFactory$","k":"def"},
{"l":"com/avast/datadog4s/StatsDMetricFactory$.html","n":"make","t":"def make[F[_]](config: StatsDMetricFactoryConfig)(using evidence$1: Sync[F]): Resource[F, MetricFactory[F]]","d":"com/avast/datadog4s/StatsDMetricFactory$","k":"def"},
{"l":"com/avast/datadog4s/StatsDMetricFactoryConfig.html","n":"StatsDMetricFactoryConfig","t":"class StatsDMetricFactoryConfig(basePrefix: Option[String], statsDServer: InetSocketAddress, defaultTags: Seq[Tag], sampleRate: Double, queueSize: Int)","d":"com/avast/datadog4s/StatsDMetricFactoryConfig","k":"class"},
{"l":"com/avast/datadog4s/api.html","n":"com.avast.datadog4s.api","t":"package com.avast.datadog4s.api","d":"com/avast/datadog4s/api","k":"package"},
{"l":"com/avast/datadog4s/api.html","n":"Tag","t":"type Tag = String","d":"com/avast/datadog4s/api","k":"type"},
{"l":"com/avast/datadog4s/api/DistributionFactory.html","n":"DistributionFactory","t":"trait DistributionFactory[F[_]]","d":"com/avast/datadog4s/api/DistributionFactory","k":"trait"},
{"l":"com/avast/datadog4s/api/DistributionFactory.html","n":"double","t":"def double(aspect: String, sampleRate: Option[Double]): Distribution[F, Double]","d":"com/avast/datadog4s/api/DistributionFactory","k":"def"},
{"l":"com/avast/datadog4s/api/DistributionFactory.html","n":"long","t":"def long(aspect: String, sampleRate: Option[Double]): Distribution[F, Long]","d":"com/avast/datadog4s/api/DistributionFactory","k":"def"},
{"l":"com/avast/datadog4s/api/GaugeFactory.html","n":"GaugeFactory","t":"trait GaugeFactory[F[_]]","d":"com/avast/datadog4s/api/GaugeFactory","k":"trait"},
{"l":"com/avast/datadog4s/api/GaugeFactory.html","n":"double","t":"def double(aspect: String, sampleRate: Option[Double]): Gauge[F, Double]","d":"com/avast/datadog4s/api/GaugeFactory","k":"def"},
{"l":"com/avast/datadog4s/api/GaugeFactory.html","n":"long","t":"def long(aspect: String, sampleRate: Option[Double]): Gauge[F, Long]","d":"com/avast/datadog4s/api/GaugeFactory","k":"def"},
{"l":"com/avast/datadog4s/api/HistogramFactory.html","n":"HistogramFactory","t":"trait HistogramFactory[F[_]]","d":"com/avast/datadog4s/api/HistogramFactory","k":"trait"},
{"l":"com/avast/datadog4s/api/HistogramFactory.html","n":"double","t":"def double(aspect: String, sampleRate: Option[Double]): Histogram[F, Double]","d":"com/avast/datadog4s/api/HistogramFactory","k":"def"},
{"l":"com/avast/datadog4s/api/HistogramFactory.html","n":"long","t":"def long(aspect: String, sampleRate: Option[Double]): Histogram[F, Long]","d":"com/avast/datadog4s/api/HistogramFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"MetricFactory","t":"trait MetricFactory[F[_]]","d":"com/avast/datadog4s/api/MetricFactory","k":"trait"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"count","t":"def count(aspect: String, sampleRate: Option[Double]): Count[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"distribution","t":"def distribution: DistributionFactory[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"gauge","t":"def gauge: GaugeFactory[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"histogram","t":"def histogram: HistogramFactory[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"timer","t":"def timer(aspect: String, sampleRate: Option[Double]): Timer[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"timer","t":"def timer: TimerFactory[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"uniqueSet","t":"def uniqueSet(aspect: String): UniqueSet[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"withScope","t":"def withScope(name: String): MetricFactory[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/MetricFactory.html","n":"withTags","t":"def withTags(tags: Tag*): MetricFactory[F]","d":"com/avast/datadog4s/api/MetricFactory","k":"def"},
{"l":"com/avast/datadog4s/api/Tag$.html","n":"Tag","t":"object Tag","d":"com/avast/datadog4s/api/Tag$","k":"object"},
{"l":"com/avast/datadog4s/api/Tag$.html","n":"of","t":"def of(k: String, v: String): Tag","d":"com/avast/datadog4s/api/Tag$","k":"def"},
{"l":"com/avast/datadog4s/api/TimerFactory.html","n":"TimerFactory","t":"trait TimerFactory[F[_]]","d":"com/avast/datadog4s/api/TimerFactory","k":"trait"},
{"l":"com/avast/datadog4s/api/TimerFactory.html","n":"distribution","t":"def distribution(aspect: String, sampleRate: Option[Double], timeUnit: TimeUnit): Timer[F]","d":"com/avast/datadog4s/api/TimerFactory","k":"def"},
{"l":"com/avast/datadog4s/api/TimerFactory.html","n":"histogram","t":"def histogram(aspect: String, sampleRate: Option[Double], timeUnit: TimeUnit): Timer[F]","d":"com/avast/datadog4s/api/TimerFactory","k":"def"},
{"l":"com/avast/datadog4s/api/metric.html","n":"com.avast.datadog4s.api.metric","t":"package com.avast.datadog4s.api.metric","d":"com/avast/datadog4s/api/metric","k":"package"},
{"l":"com/avast/datadog4s/api/metric/Count.html","n":"Count","t":"trait Count[F[_]]","d":"com/avast/datadog4s/api/metric/Count","k":"trait"},
{"l":"com/avast/datadog4s/api/metric/Count.html","n":"dec","t":"def dec(tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/Count","k":"def"},
{"l":"com/avast/datadog4s/api/metric/Count.html","n":"inc","t":"def inc(tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/Count","k":"def"},
{"l":"com/avast/datadog4s/api/metric/Count.html","n":"modify","t":"def modify(delta: Int, tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/Count","k":"def"},
{"l":"com/avast/datadog4s/api/metric/Distribution.html","n":"Distribution","t":"trait Distribution[F[_], N]","d":"com/avast/datadog4s/api/metric/Distribution","k":"trait"},
{"l":"com/avast/datadog4s/api/metric/Distribution.html","n":"record","t":"def record(value: N, tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/Distribution","k":"def"},
{"l":"com/avast/datadog4s/api/metric/ElapsedTime.html","n":"ElapsedTime","t":"trait ElapsedTime[A]","d":"com/avast/datadog4s/api/metric/ElapsedTime","k":"trait"},
{"l":"com/avast/datadog4s/api/metric/ElapsedTime.html","n":"amount","t":"def amount(instance: A, timeUnit: TimeUnit): Long","d":"com/avast/datadog4s/api/metric/ElapsedTime","k":"def"},
{"l":"com/avast/datadog4s/api/metric/ElapsedTime.html","n":"contraMap","t":"def contraMap[B](f: B => A): ElapsedTime[B]","d":"com/avast/datadog4s/api/metric/ElapsedTime","k":"def"},
{"l":"com/avast/datadog4s/api/metric/ElapsedTime$.html","n":"ElapsedTime","t":"object ElapsedTime","d":"com/avast/datadog4s/api/metric/ElapsedTime$","k":"object"},
{"l":"com/avast/datadog4s/api/metric/ElapsedTime$.html","n":"apply","t":"def apply[A](using evidence$1: ElapsedTime[A]): ElapsedTime[A]","d":"com/avast/datadog4s/api/metric/ElapsedTime$","k":"def"},
{"l":"com/avast/datadog4s/api/metric/ElapsedTime$.html","n":"durationInstance","t":"val durationInstance: ElapsedTime[Duration]","d":"com/avast/datadog4s/api/metric/ElapsedTime$","k":"val"},
{"l":"com/avast/datadog4s/api/metric/ElapsedTime$.html","n":"finiteDurationInstance","t":"val finiteDurationInstance: ElapsedTime[FiniteDuration]","d":"com/avast/datadog4s/api/metric/ElapsedTime$","k":"val"},
{"l":"com/avast/datadog4s/api/metric/Gauge.html","n":"Gauge","t":"trait Gauge[F[_], N]","d":"com/avast/datadog4s/api/metric/Gauge","k":"trait"},
{"l":"com/avast/datadog4s/api/metric/Gauge.html","n":"set","t":"def set(value: N, tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/Gauge","k":"def"},
{"l":"com/avast/datadog4s/api/metric/Histogram.html","n":"Histogram","t":"trait Histogram[F[_], N]","d":"com/avast/datadog4s/api/metric/Histogram","k":"trait"},
{"l":"com/avast/datadog4s/api/metric/Histogram.html","n":"record","t":"def record(value: N, tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/Histogram","k":"def"},
{"l":"com/avast/datadog4s/api/metric/Timer.html","n":"Timer","t":"trait Timer[F[_]]","d":"com/avast/datadog4s/api/metric/Timer","k":"trait"},
{"l":"com/avast/datadog4s/api/metric/Timer.html","n":"record","t":"def record[T](value: T, tags: Tag*)(using evidence$1: ElapsedTime[T]): F[Unit]","d":"com/avast/datadog4s/api/metric/Timer","k":"def"},
{"l":"com/avast/datadog4s/api/metric/Timer.html","n":"recordTime","t":"def recordTime(elapsed: Long, timeUnit: TimeUnit, tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/Timer","k":"def"},
{"l":"com/avast/datadog4s/api/metric/Timer.html","n":"time","t":"def time[A](f: F[A], tags: Tag*): F[A]","d":"com/avast/datadog4s/api/metric/Timer","k":"def"},
{"l":"com/avast/datadog4s/api/metric/UniqueSet.html","n":"UniqueSet","t":"trait UniqueSet[F[_]]","d":"com/avast/datadog4s/api/metric/UniqueSet","k":"trait"},
{"l":"com/avast/datadog4s/api/metric/UniqueSet.html","n":"record","t":"def record(value: String, tags: Tag*): F[Unit]","d":"com/avast/datadog4s/api/metric/UniqueSet","k":"def"},
{"l":"com/avast/datadog4s/api/tag.html","n":"com.avast.datadog4s.api.tag","t":"package com.avast.datadog4s.api.tag","d":"com/avast/datadog4s/api/tag","k":"package"},
{"l":"com/avast/datadog4s/api/tag/TagValue.html","n":"TagValue","t":"trait TagValue[A]","d":"com/avast/datadog4s/api/tag/TagValue","k":"trait"},
{"l":"com/avast/datadog4s/api/tag/TagValue.html","n":"contramap","t":"def contramap[B](f: B => A): TagValue[B]","d":"com/avast/datadog4s/api/tag/TagValue","k":"def"},
{"l":"com/avast/datadog4s/api/tag/TagValue.html","n":"convert","t":"def convert(a: A): String","d":"com/avast/datadog4s/api/tag/TagValue","k":"def"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"TagValue","t":"object TagValue","d":"com/avast/datadog4s/api/tag/TagValue$","k":"object"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"apply","t":"def apply[A](using evidence$1: TagValue[A]): TagValue[A]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"def"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"booleanTagValue","t":"val booleanTagValue: TagValue[Boolean]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"classTagValue","t":"val classTagValue: TagValue[Class[_]]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"doubleTagValue","t":"val doubleTagValue: TagValue[Double]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"exceptionTagValue","t":"val exceptionTagValue: TagValue[Exception]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"floatTagValue","t":"val floatTagValue: TagValue[Float]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"intTagValue","t":"val intTagValue: TagValue[Int]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"longTagValue","t":"val longTagValue: TagValue[Long]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"shortTagValue","t":"val shortTagValue: TagValue[Short]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"stringTagValue","t":"val stringTagValue: TagValue[String]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/TagValue$.html","n":"throwableTagValue","t":"val throwableTagValue: TagValue[Throwable]","d":"com/avast/datadog4s/api/tag/TagValue$","k":"val"},
{"l":"com/avast/datadog4s/api/tag/Tagger.html","n":"Tagger","t":"trait Tagger[A]","d":"com/avast/datadog4s/api/tag/Tagger","k":"trait"},
{"l":"com/avast/datadog4s/api/tag/Tagger.html","n":"tag","t":"def tag(a: A): Tag","d":"com/avast/datadog4s/api/tag/Tagger","k":"def"},
{"l":"com/avast/datadog4s/api/tag/Tagger$.html","n":"Tagger","t":"object Tagger","d":"com/avast/datadog4s/api/tag/Tagger$","k":"object"},
{"l":"com/avast/datadog4s/api/tag/Tagger$.html","n":"make","t":"def make[A](name: String)(using evidence$1: TagValue[A]): Tagger[A]","d":"com/avast/datadog4s/api/tag/Tagger$","k":"def"},
{"l":"com/avast/datadog4s/extension/http4s.html","n":"com.avast.datadog4s.extension.http4s","t":"package com.avast.datadog4s.extension.http4s","d":"com/avast/datadog4s/extension/http4s","k":"package"},
{"l":"com/avast/datadog4s/extension/http4s.html","n":"methodTagValue","t":"val methodTagValue: TagValue[Method]","d":"com/avast/datadog4s/extension/http4s","k":"val"},
{"l":"com/avast/datadog4s/extension/http4s.html","n":"statusTagValue","t":"val statusTagValue: TagValue[Status]","d":"com/avast/datadog4s/extension/http4s","k":"val"},
{"l":"com/avast/datadog4s/extension/http4s.html","n":"terminationTypeTagValue","t":"val terminationTypeTagValue: TagValue[TerminationType]","d":"com/avast/datadog4s/extension/http4s","k":"val"},
{"l":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$.html","n":"DatadogMetricsOps","t":"object DatadogMetricsOps","d":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$","k":"object"},
{"l":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$.html","n":"ClassifierTags","t":"type ClassifierTags = String => List[Tag]","d":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$","k":"type"},
{"l":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$.html","n":"builder","t":"def builder[F[_]](metricFactory: MetricFactory[F])(using evidence$1: Sync[F]): MetricsOpsBuilder[F]","d":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$","k":"def"},
{"l":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$.html","n":"make","t":"def make[F[_]](metricFactory: MetricFactory[F], classifierTags: ClassifierTags)(implicit F: Sync[F]): F[MetricsOps[F]]","d":"com/avast/datadog4s/extension/http4s/DatadogMetricsOps$","k":"def"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder.html","n":"MetricsOpsBuilder","t":"class MetricsOpsBuilder[F[_]]","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder","k":"class"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder.html","n":"build","t":"def build(): F[MetricsOps[F]]","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder","k":"def"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder.html","n":"setClassifierTags","t":"def setClassifierTags(newClassifierTags: ClassifierTags): MetricsOpsBuilder[F]","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder","k":"def"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder.html","n":"useDistributionBasedTimers","t":"def useDistributionBasedTimers(): MetricsOpsBuilder[F]","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder","k":"def"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder.html","n":"useHistogramBasedTimers","t":"def useHistogramBasedTimers(): MetricsOpsBuilder[F]","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder","k":"def"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder$.html","n":"MetricsOpsBuilder","t":"object MetricsOpsBuilder","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder$","k":"object"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder$.html","n":"defaultClassifierTags","t":"val defaultClassifierTags: ClassifierTags","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder$","k":"val"},
{"l":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder$.html","n":"withDefaults","t":"def withDefaults[F[_]](metricFactory: MetricFactory[F])(using evidence$2: Sync[F]): MetricsOpsBuilder[F]","d":"com/avast/datadog4s/extension/http4s/MetricsOpsBuilder$","k":"def"},
{"l":"com/avast/datadog4s/extension/jvm.html","n":"com.avast.datadog4s.extension.jvm","t":"package com.avast.datadog4s.extension.jvm","d":"com/avast/datadog4s/extension/jvm","k":"package"},
{"l":"com/avast/datadog4s/extension/jvm/JvmMonitoring$.html","n":"JvmMonitoring","t":"object JvmMonitoring","d":"com/avast/datadog4s/extension/jvm/JvmMonitoring$","k":"object"},
{"l":"com/avast/datadog4s/extension/jvm/JvmMonitoring$.html","n":"ErrorHandler","t":"type ErrorHandler[F[_]] = Throwable => F[Unit]","d":"com/avast/datadog4s/extension/jvm/JvmMonitoring$","k":"type"},
{"l":"com/avast/datadog4s/extension/jvm/JvmMonitoring$.html","n":"configured","t":"def configured[F[_]](factory: MetricFactory[F], config: Config, errorHandler: () => F)(using evidence$3: Sync[F], evidence$4: Temporal[F]): Resource[F, Unit]","d":"com/avast/datadog4s/extension/jvm/JvmMonitoring$","k":"def"},
{"l":"com/avast/datadog4s/extension/jvm/JvmMonitoring$.html","n":"default","t":"def default[F[_]](factory: MetricFactory[F])(using evidence$1: Sync[F], evidence$2: Temporal[F]): Resource[F, Unit]","d":"com/avast/datadog4s/extension/jvm/JvmMonitoring$","k":"def"},
{"l":"com/avast/datadog4s/extension/jvm/JvmMonitoring$$Config.html","n":"Config","t":"class Config(delay: Duration, timeout: Duration)","d":"com/avast/datadog4s/extension/jvm/JvmMonitoring$$Config","k":"class"},
{"l":"com/avast/datadog4s/extension/jvm/JvmReporter.html","n":"JvmReporter","t":"class JvmReporter[F[_]](metricsFactory: MetricFactory[F])(using evidence$1: Sync[F])","d":"com/avast/datadog4s/extension/jvm/JvmReporter","k":"class"},
{"l":"com/avast/datadog4s/extension/jvm/JvmReporter.html","n":"collect","t":"val collect: F[Unit]","d":"com/avast/datadog4s/extension/jvm/JvmReporter","k":"val"},
{"l":"com/avast/datadog4s/noop.html","n":"com.avast.datadog4s.noop","t":"package com.avast.datadog4s.noop","d":"com/avast/datadog4s/noop","k":"package"},
{"l":"com/avast/datadog4s/noop/NoopMetricFactory.html","n":"NoopMetricFactory","t":"class NoopMetricFactory[F[_]] extends MetricFactory[F]","d":"com/avast/datadog4s/noop/NoopMetricFactory","k":"class"},
{"l":"com/avast/datadog4s/noop/metric.html","n":"com.avast.datadog4s.noop.metric","t":"package com.avast.datadog4s.noop.metric","d":"com/avast/datadog4s/noop/metric","k":"package"},
{"l":"com/avast/datadog4s/noop/metric/NoopCount.html","n":"NoopCount","t":"class NoopCount[F[_]] extends Count[F]","d":"com/avast/datadog4s/noop/metric/NoopCount","k":"class"},
{"l":"com/avast/datadog4s/noop/metric/NoopDistribution.html","n":"NoopDistribution","t":"class NoopDistribution[F[_], N] extends Distribution[F, N]","d":"com/avast/datadog4s/noop/metric/NoopDistribution","k":"class"},
{"l":"com/avast/datadog4s/noop/metric/NoopGauge.html","n":"NoopGauge","t":"class NoopGauge[F[_], N] extends Gauge[F, N]","d":"com/avast/datadog4s/noop/metric/NoopGauge","k":"class"},
{"l":"com/avast/datadog4s/noop/metric/NoopHistogram.html","n":"NoopHistogram","t":"class NoopHistogram[F[_], N] extends Histogram[F, N]","d":"com/avast/datadog4s/noop/metric/NoopHistogram","k":"class"},
{"l":"com/avast/datadog4s/noop/metric/NoopTimer.html","n":"NoopTimer","t":"class NoopTimer[F[_]] extends Timer[F]","d":"com/avast/datadog4s/noop/metric/NoopTimer","k":"class"},
{"l":"com/avast/datadog4s/noop/metric/NoopUniqueSet.html","n":"NoopUniqueSet","t":"class NoopUniqueSet[F[_]] extends UniqueSet[F]","d":"com/avast/datadog4s/noop/metric/NoopUniqueSet","k":"class"},
{"l":"com/avast/datadog4s/playground.html","n":"com.avast.datadog4s.playground","t":"package com.avast.datadog4s.playground","d":"com/avast/datadog4s/playground","k":"package"},
{"l":"com/avast/datadog4s/playground/CreateMetric$.html","n":"CreateMetric","t":"object CreateMetric extends IOApp","d":"com/avast/datadog4s/playground/CreateMetric$","k":"object"},
{"l":"com/avast/datadog4s/playground/CreateMetric$.html","n":"loop","t":"def loop(drawProgressBar: IO[Unit], hist: Histogram[IO, Long], dist: Distribution[IO, Long]): IO[Unit]","d":"com/avast/datadog4s/playground/CreateMetric$","k":"def"},
{"l":"com/avast/datadog4s/statsd.html","n":"com.avast.datadog4s.statsd","t":"package com.avast.datadog4s.statsd","d":"com/avast/datadog4s/statsd","k":"package"},
{"l":"com/avast/datadog4s/statsd/StatsDClient$.html","n":"StatsDClient","t":"object StatsDClient","d":"com/avast/datadog4s/statsd/StatsDClient$","k":"object"},
{"l":"com/avast/datadog4s/statsd/StatsDClient$.html","n":"fromBuilder","t":"def fromBuilder[F[_]](builder: NonBlockingStatsDClientBuilder)(using evidence$1: Sync[F]): Resource[F, NonBlockingStatsDClient]","d":"com/avast/datadog4s/statsd/StatsDClient$","k":"def"},
{"l":"com/avast/datadog4s/statsd/StatsDClient$.html","n":"make","t":"def make[F[_]](statsDServer: InetSocketAddress, queueSize: Int)(using evidence$2: Sync[F]): Resource[F, NonBlockingStatsDClient]","d":"com/avast/datadog4s/statsd/StatsDClient$","k":"def"},
{"l":"com/avast/datadog4s/statsd/StatsDClient$.html","n":"makeUnsafe","t":"def makeUnsafe(statsDServer: InetSocketAddress, queueSize: Int): NonBlockingStatsDClient","d":"com/avast/datadog4s/statsd/StatsDClient$","k":"def"},
{"l":"com/avast/datadog4s/statsd/StatsDMetricFactory.html","n":"StatsDMetricFactory","t":"class StatsDMetricFactory[F[_]](statsDClient: StatsDClient, prefix: Option[String], defaultSampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends MetricFactory[F]","d":"com/avast/datadog4s/statsd/StatsDMetricFactory","k":"class"},
{"l":"com/avast/datadog4s/statsd/StatsDMetricFactory.html","n":"distribution","t":"val distribution: DistributionFactory[F]","d":"com/avast/datadog4s/statsd/StatsDMetricFactory","k":"val"},
{"l":"com/avast/datadog4s/statsd/StatsDMetricFactory.html","n":"gauge","t":"val gauge: GaugeFactory[F]","d":"com/avast/datadog4s/statsd/StatsDMetricFactory","k":"val"},
{"l":"com/avast/datadog4s/statsd/StatsDMetricFactory.html","n":"histogram","t":"val histogram: HistogramFactory[F]","d":"com/avast/datadog4s/statsd/StatsDMetricFactory","k":"val"},
{"l":"com/avast/datadog4s/statsd/StatsDMetricFactory.html","n":"timer","t":"val timer: TimerFactory[F]","d":"com/avast/datadog4s/statsd/StatsDMetricFactory","k":"val"},
{"l":"com/avast/datadog4s/statsd/metric.html","n":"com.avast.datadog4s.statsd.metric","t":"package com.avast.datadog4s.statsd.metric","d":"com/avast/datadog4s/statsd/metric","k":"package"},
{"l":"com/avast/datadog4s/statsd/metric/CountImpl.html","n":"CountImpl","t":"class CountImpl[F[_]](statsDClient: StatsDClient, prefix: String, sampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends Count[F]","d":"com/avast/datadog4s/statsd/metric/CountImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/DistributionDoubleImpl.html","n":"DistributionDoubleImpl","t":"class DistributionDoubleImpl[F[_]](statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends Distribution[F, Double]","d":"com/avast/datadog4s/statsd/metric/DistributionDoubleImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/DistributionLongImpl.html","n":"DistributionLongImpl","t":"class DistributionLongImpl[F[_]](statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends Distribution[F, Long]","d":"com/avast/datadog4s/statsd/metric/DistributionLongImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/GaugeDoubleImpl.html","n":"GaugeDoubleImpl","t":"class GaugeDoubleImpl[F[_]](statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends Gauge[F, Double]","d":"com/avast/datadog4s/statsd/metric/GaugeDoubleImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/GaugeLongImpl.html","n":"GaugeLongImpl","t":"class GaugeLongImpl[F[_]](statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends Gauge[F, Long]","d":"com/avast/datadog4s/statsd/metric/GaugeLongImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/HistogramDoubleImpl.html","n":"HistogramDoubleImpl","t":"class HistogramDoubleImpl[F[_]](statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends Histogram[F, Double]","d":"com/avast/datadog4s/statsd/metric/HistogramDoubleImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/HistogramLongImpl.html","n":"HistogramLongImpl","t":"class HistogramLongImpl[F[_]](statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends Histogram[F, Long]","d":"com/avast/datadog4s/statsd/metric/HistogramLongImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/TimerImpl.html","n":"TimerImpl","t":"class TimerImpl[F[_]](clock: Clock[F])(using evidence$1: Sync[F]) extends Timer[F]","d":"com/avast/datadog4s/statsd/metric/TimerImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/UniqueSetImpl.html","n":"UniqueSetImpl","t":"class UniqueSetImpl[F[_]](statsDClient: StatsDClient, aspect: String, defaultTags: Seq[Tag])(using evidence$1: Sync[F]) extends UniqueSet[F]","d":"com/avast/datadog4s/statsd/metric/UniqueSetImpl","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/timer.html","n":"com.avast.datadog4s.statsd.metric.timer","t":"package com.avast.datadog4s.statsd.metric.timer","d":"com/avast/datadog4s/statsd/metric/timer","k":"package"},
{"l":"com/avast/datadog4s/statsd/metric/timer/DistributionTimer.html","n":"DistributionTimer","t":"class DistributionTimer[F[_]](clock: Clock[F], statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag], timeUnit: TimeUnit)(using evidence$1: Sync[F]) extends TimerImpl[F]","d":"com/avast/datadog4s/statsd/metric/timer/DistributionTimer","k":"class"},
{"l":"com/avast/datadog4s/statsd/metric/timer/HistogramTimer.html","n":"HistogramTimer","t":"class HistogramTimer[F[_]](clock: Clock[F], statsDClient: StatsDClient, aspect: String, sampleRate: Double, defaultTags: Seq[Tag], timeUnit: TimeUnit)(using evidence$1: Sync[F]) extends TimerImpl[F]","d":"com/avast/datadog4s/statsd/metric/timer/HistogramTimer","k":"class"},
{"l":"docs/index.html","n":"site","t":"site","d":"","k":"static"}];